# Generated by Django 5.2.3 on 2025-06-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Academies',
            },
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academies.academy')),
            ],
        ),
    ]
