# Generated by Django 5.2.3 on 2025-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Academies'},
        ),
        migrations.AddField(
            model_name='academy',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the academy'),
        ),
        migrations.AddField(
            model_name='academy',
            name='logo_url',
            field=models.URLField(blank=True, help_text="URL to the academy's logo image"),
        ),
        migrations.AddField(
            model_name='academy',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which this academy appears'),
        ),
    ]
