# Generated by Django 5.2.3 on 2025-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_alter_academy_options_academy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academy',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='academy',
            name='logo',
            field=models.ImageField(blank=True, help_text='Academy logo image', null=True, upload_to='academy_logos/'),
        ),
    ]
