# Generated by Django 5.2.3 on 2025-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_remove_academy_logo_url_academy_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the category page'),
        ),
    ]
