# Generated by Django 5.2.3 on 2025-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0005_offering_categories_alter_offering_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering',
            name='description',
            field=models.TextField(blank=True, help_text='Course description (can contain HTML)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='program_content',
            field=models.TextField(blank=True, help_text='Detailed program content (can contain HTML)'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks (can contain HTML)'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.TextField(blank=True, help_text='Variation-specific description (can contain HTML)'),
        ),
    ]
