# Generated by Django 5.2.3 on 2025-06-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0006_alter_offering_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction text from academy homepage (may contain HTML)'),
        ),
    ]
