# Generated by Django 5.2.3 on 2025-06-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0007_academy_introduction'),
    ]

    operations = [
    ]
