# Generated by Django 5.2.3 on 2025-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0008_auto_20250623_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, help_text='Teacher description from profile page (can contain HTML)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True, help_text="URL to teacher's photo"),
        ),
    ]
